# Generated by Django 3.1.1 on 2020-11-06 15:28

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('texto', models.TextField()),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='intro/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Introducción',
            },
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Quienes Somos',
            },
        ),
    ]
