# Generated by Django 3.1.1 on 2020-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
    ]
