# Generated by Django 3.1.4 on 2021-05-12 16:35

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20201127_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contectenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antes_de_contactarnos', models.TextField()),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.URLField()),
                ('telefono', models.CharField(max_length=250)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contáctenos',
            },
        ),
        migrations.AddField(
            model_name='introduccion',
            name='link_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introduccion',
            name='link_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introduccion',
            name='link_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
