# Generated by Django 3.1.4 on 2021-05-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_remove_contectenos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectenos',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contectenos',
            name='telefono',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
