# Generated by Django 3.1.4 on 2021-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_auto_20210517_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contectenos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='contectenos',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='contectenos',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
