# Generated by Django 3.1.1 on 2020-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0002_remove_cursos_imagen_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
