# Generated by Django 3.1.1 on 2020-11-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0005_auto_20200925_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
    ]
