# Generated by Django 3.1.1 on 2020-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0006_auto_20201106_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
