# Generated by Django 3.1.1 on 2020-11-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0007_reflexion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflexion',
            options={'verbose_name': 'Reflexión', 'verbose_name_plural': 'Reflexiones'},
        ),
    ]
