# Generated by Django 3.1.4 on 2020-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0008_auto_20201127_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflexion',
            name='autor',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
