# Generated by Django 3.1.4 on 2021-03-03 15:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0009_reflexion_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprende.cursos', verbose_name='Sesión'),
        ),
        migrations.AlterField(
            model_name='reflexion',
            name='autor',
            field=models.CharField(max_length=300, verbose_name='Autor/Fuente'),
        ),
    ]
