# Generated by Django 3.1.4 on 2021-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0010_auto_20210303_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='destacado',
            field=models.BooleanField(default=True),
        ),
    ]
