# Generated by Django 3.1.1 on 2020-09-02 16:36

import ckeditor_uploader.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='lugar.departamento')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='lugar.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.pais')),
            ],
            options={
                'verbose_name_plural': 'Escuelas',
            },
        ),
    ]
