# Generated by Django 3.1.1 on 2020-09-02 17:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20200902_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='galeria/')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liderazgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='liderazgo/')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='galeria/imagenes/')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.galeria')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='eventos/')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('lugar', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='biblioteca/')),
                ('archivo', models.FileField(upload_to='documentos-biblioteca/')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='Actualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='actualidad/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Actualidad',
            },
        ),
    ]
