# Generated by Django 3.1.1 on 2020-09-11 20:43

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_actualidad_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='escuela',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escuela',
            name='lugar',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
