# Generated by Django 3.1.1 on 2020-11-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200911_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualidad',
            options={'verbose_name_plural': 'Acontecimientos'},
        ),
    ]
