# Generated by Django 3.1.1 on 2020-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201106_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualidad',
            options={'verbose_name': 'acontecimiento', 'verbose_name_plural': 'Acontecimientos'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
