# Generated by Django 3.1.1 on 2020-11-27 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201127_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'verbose_name': 'recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tiporecurso'),
        ),
    ]
