# Generated by Django 3.1.1 on 2020-11-27 15:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201127_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.AddField(
            model_name='escuela',
            name='hombres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='mujeres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.fases'),
        ),
    ]
