# Generated by Django 3.1.1 on 2020-11-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201127_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuela')),
            ],
            options={
                'verbose_name_plural': 'Emprendimientos',
            },
        ),
    ]
