# Generated by Django 3.1.1 on 2020-11-27 16:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0010_emprendimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLiderazgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='actualidad/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experiencia de liderazgo',
                'verbose_name_plural': 'Experiencias de Liderazgo',
            },
        ),
    ]
