# Generated by Django 3.1.4 on 2020-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_experiencialiderazgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
