# Generated by Django 3.1.4 on 2021-03-03 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('web', '0012_auto_20201214_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='fase',
        ),
        migrations.AddField(
            model_name='emprendimientos',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tipoemprendimiento'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='area_trabajo',
            field=models.ManyToManyField(blank=True, to='monitoreo.AreaTrabajo', verbose_name='Área de trabajo'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='cargo_referencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='correo_referencia',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='fundacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escuela',
            name='nombre_referencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='otros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='talleres_impartidos',
            field=models.ManyToManyField(blank=True, to='monitoreo.Talleres'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='telefono_referencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='tipo_organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.tipoorganizacion', verbose_name='Tipo de organización'),
        ),
        migrations.DeleteModel(
            name='Fases',
        ),
    ]
