# Generated by Django 3.1.4 on 2021-03-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210303_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name': 'Núcleo', 'verbose_name_plural': 'Núcleos'},
        ),
    ]
