# Generated by Django 3.1.4 on 2021-03-25 17:13

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210323_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosEmprendimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='emprendimientos/')),
                ('emprendimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.emprendimientos')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
