# Generated by Django 3.1.4 on 2021-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_fotosemprendimientos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualidad',
            options={'verbose_name': 'noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
