# Generated by Django 3.1.4 on 2021-03-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_formadores_participantes_perfilvocacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HomologacionFondos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField()),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.rubro')),
            ],
            options={
                'verbose_name': 'Homologación de Fondos',
                'verbose_name_plural': 'Homologación de Fondos',
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20)),
                ('ejecucion', models.FloatField()),
                ('homologacion_fondos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.homologacionfondos')),
            ],
            options={
                'verbose_name_plural': 'Ejecución',
            },
        ),
    ]
