# Generated by Django 3.1.4 on 2021-03-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_ejecucion_homologacionfondos_rubro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecucion',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='ejecucion',
            name='homologacion_fondos',
        ),
        migrations.CreateModel(
            name='AnioEjecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('homologacion_fondos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.homologacionfondos')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='anioejecucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.anioejecucion'),
            preserve_default=False,
        ),
    ]
