# Generated by Django 3.1.4 on 2021-04-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_auto_20210412_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.rubro')),
            ],
        ),
    ]
