# Generated by Django 3.1.4 on 2021-04-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_auto_20210419_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anioejecucion',
            name='homologacion_fondos',
        ),
        migrations.AddField(
            model_name='anioejecucion',
            name='presupuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoreo.presupuesto'),
            preserve_default=False,
        ),
    ]
