# Generated by Django 3.1.4 on 2021-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0007_auto_20210429_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
